### PR TITLE
minor improvements

### PR DESCRIPTION
**Pull request by mikesmullin**
disabling requirement to set :user. 
also opening the possibility to set :package_manager, "apt-fast" for example.

### CODE REVIEW

**Comment by iain** [comment]
Thanks, look very interesting. Can you make both properties default?

Like this:

``` ruby
set_default(:current_user) { capture('whoami').strip }
set_default :package_manager, "apt-get"
```

This way, it will be listed in `cap roundsman:configuration`, thus being discoverable.

**Comment by mikesmullin** [comment]
take a look
seems to be working here

**Comment by mikesmullin** [comment]
ok i see chown was necessary. so i made a default setting called :roundsman_user as you suggested. look now

**Comment by mikesmullin** [comment]
also found this which appears to be a bug as far as i can tell. took me a while to figure out where the password prompt was coming from.

**Comment by mikesmullin** [comment]
let me know if there is anything else i can do to get this merged. would rather not maintain my own separate fork if at all possible. :)

**Comment by iain** [comment]
Understood. I will get to it later, when I have some more time.

**Comment by mikesmullin** [comment]
its a good change i promise :D

**Pull request merged**
