### PR TITLE
Speed up building ruby..

### PR DESCRIPTION
**Pull request by Flamefork**
.. by 30..40%.

Not sure if this options work across ruby implementations other than MRI & YARV, still I doubt anyone would run chef this way.

### CODE REVIEW

**Comment by mugwump** [comment]
+1 - the ruby-build is terribly slow, it even looks like it's hanging sometimes: I'm not sure that the optimisation will fix that, but if anyone has an idea why it should take more than half an hour to build ruby I'd be grateful...

**Comment by Flamefork** [comment]
@mugwump ruby-build is slow just cause compiling ruby takes time. As of my experience, more than half an hour is the time to compile ruby only on very slow machine, like AWS micro instance (I actually use such instances for few projects). And generating rdocs take about 40% of total build time, so speed-up is real :)

**Comment by mugwump** [comment]
it's not only speedup I' afraid: Even installing rake with rdoc chokes on the microinstances. Maybe it's not a problem on bigger machines, but a switch would definitely be very useful.

**Comment by iain** [comment]
sorry, completely missed this pull request

**Pull request merged**
